//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Note
    {
        public int ID { get; set; }
        public string Note_Des { get; set; }
        public string Note_Manger { get; set; }
        public string Note_User { get; set; }
    }
}
